---
title: "macroAnalysis_YourNAME"
subtitle: "BIO 131 Macroinvertebrate Data Analysis"
author: "Your Name"
date: "November , 2025"
format: 
  html:
    code-overflow: wrap
    embed-resources: true
---


# Render this File to HTML & Print to PDF

Don't forget to "render" your .qmd file when you are done.

-   Before you Render

    -   Make sure that each code chunk has an unique label name or no name

    -   Save this file and give it the name "macroAnalysis_YourName.qmd" (replace your name for "YourName" with no spaces)

-   Render this Quarto file to HTML (just select the Render menu item at the top of this window)

-   If the HTML file didn't already open in your browser, then click on the name of the file in the Files window and select "View in Web Browser"

-   Once the HTML file is open in your web browser, then use the print function within your browser to save it as a PDF. Please name your PDF file "macroAnalysis_YourName.pdf" (replace your name for "YourName" with no spaces)

-   Make sure the PDF file is saved somewhere on your computer that you can get to

-   Place a copy of the PDF file in your Individual Google Drive folder for this class
